### ISSUE TITLE
Bug when creating an MPS with length 1

### ISSUE THREAD

**Issue by manuschneider** [mcbapo/mpsdyn#1]
If I try `MPS state(1, 1, 1);`, I get a memory leak;

This can be simply fixed by replacing
```
dimensions[2]=1;
A[length-1]=new Site_t(length,dimensions);
```
in `MPS::MPS(int len,int bon,int d)` with the conditional statement
```
if(length>1){
    dimensions[2]=1;
    A[length-1]=new Site_t(length,dimensions);
}
```

**Comment by mcbapo** [comment]
Hi, Manuel,

Thanks. Yes, you are totally right. I noticed a problem with length 1 some
time ago, but never looked into it. Thanks!!

Best,

Mari Carmen
