### ISSUE TITLE
Small bug in MPO::markAsOwn

### ISSUE THREAD

**Issue by manuschneider** [mcbapo/mpsdyn#3]
A loop in MPO::markAsOwn starts from 1 instead of 0, this does not seem to be intended.
Here the corrected version in MPO.cpp:
```
void MPO::markAsOwn(int pos){
  if(!myown){
    myown=1;
    myops=new bool[length];
    for(int i=0;i<length;i++)
      myops[i]=0;
  }
  myops[pos]=1;
}
```
This should not cause serious problems, but might cause memory leaks because the operators are not deleted from memory correctly.

**Comment by mcbapo** [comment]
Thanks, Manuel! 
But the code in github seems identical to what you send (the loop starts in 0, too)

**Comment by mcbapo** [comment]
Ok, I got it. I had corrected this 11 months ago in the original branch, but in your code it was still with the bug. Fixed, thanks!
